core/accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='user_profile'),
    path('logout/', views.LogoutUserView.as_view(), name='user_logout'),
    path("register/", views.UserRegisterView.as_view(), name="user_register"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("edit/", views.EditProfileView.as_view(), name="user_edit"),
    path('api/v1/', include('accounts.api.v1.urls')),
    # path("api/v2/", include("djoser.urls")),
    # path("api/v2/", include("djoser.urls.jwt")),
]

core/blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('post/detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    #
    path("api/v1/", include("blog.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="ToDo API",
        default_version="v1",
        description="this is a test api for ToDo App",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="akbar.beiramzadeh@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[
        permissions.AllowAny,
    ],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('comment/', include('comment.urls', namespace='comment')),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

core/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

core/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-nav">
      <a class="nav-link active" href="{% url 'blog:home' %}">Home</a>
      {% if request.user.is_authenticated %}
      <a class="nav-link active" href="{% url 'accounts:user_profile' request.user.id %}">Profile</a>
      <a class="nav-link active" href="{% url 'accounts:user_logout' %}">Logout</a>
      {% else %}
      <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
      <a class="nav-link active" href="{% url 'accounts:user_login' %}">Login</a>
      {% endif %}
    </div>
  </div>
</nav>